name: CI - Containerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub (optional, if pushing to DockerHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t booker-api-test:latest -f ./Githu/booking/BookerApiTest/Dockerfile .

    # Step 5: Run the container
    - name: Run container
      run: |
        docker run -d -p 8000:8000 --name booker-api-test-container booker-api-test:latest

    # Step 6: Verify the Allure report is served
    - name: Verify Allure Report
      run: |
        curl -I http://localhost:8000