name: CI - Containerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub (optional, if pushing to DockerHub)
    # Commented out as per the requirement
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        pwd
        ls
        ls -la
        docker build -t booker-api-test:latest -f ./BookerApiTest/Dockerfile .

    # Step 5: Run the container and execute tests
    - name: Run tests inside the container
      run: |
        pwd
        ls
        ls -la
        #docker run --rm booker-api-test:latest dotnet test --logger "trx;LogFileName=test-results.trx" || true
        #docker run --rm booker-api-test:latest allure generate /app/BookerApiTest/bin/Debug/net8.0/allure-results -o ./allure-report --clean
        
        # Run tests and generate allure-results
        docker run --rm -v /runner/work/booking/booking/BookerApiTest:/app/BookerApiTest booker-api-test:latest dotnet test --logger "trx;LogFileName=test-results.trx" || true
        # Generate Allure report
        docker run --rm -v /runner/work/booking/booking/BookerApiTest:/app/BookerApiTest -v /runner/work/booking/booking/allure-report:/app/allure-report booker-api-test:latest allure generate /app/BookerApiTest/bin/Debug/net8.0/allure-results -o /app/allure-report --clean
        echo ",,,,,,,,,,,,,,22222222,,,"
        
        ls -la
        
        echo ",,,,,,,,,,,,,,,,,"
        ls -la /runner/work/booking/booking/BookerApiTest
        echo "-----------111---------"
        ls -la /runner/work/booking/booking/BookerApiTest/bin
        echo "-----------111---------"
        ls -la /runner/work/booking/booking/BookerApiTest/bin/Debug
        echo "-----------111---------"
        ls -la /runner/work/booking/booking/BookerApiTest/bin/Debug/net8.0
        echo "-----------111---------"
        sudo ls -la /runner/work/booking/booking/BookerApiTest/bin/Debug/net8.0/allure-results
        echo "--------------------"
        

    # Step 5: Upload raw test results (.trx file)
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./BookerApiTest/TestResults/test-results.trx

    # Step 6: Upload Allure results
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./BookerApiTest/bin/Debug/net8.0/allure-results