name: CI - Containerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Commented out as per the requirement
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t booker-api-test:latest -f ./BookerApiTest/Dockerfile .

    - name: Create directories
      run: mkdir -p ./bin ./TestResults

    - name: Build with Docker
      run: |
        docker run --rm \
          -v $(pwd)/bin:/app/BookerApiTest/bin \
          booker-api-test:latest \
          dotnet build
  
    - name: Run Tests with Docker
      run: |
        docker run --rm \
            -v $(pwd)/bin:/app/BookerApiTest/bin \
            -v $(pwd)/TestResults:/app/BookerApiTest/TestResults \
            booker-api-test:latest \
            dotnet test --logger "trx;LogFileName=test-results.trx" || true

    # Step 5: Upload test results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./bin/Debug/net8.0/allure-results

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: raw-results
        path: ./TestResults