name: CI - Containerized Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub (optional, if pushing to DockerHub)
    # Commented out as per the requirement
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        pwd
        ls
        ls -la
        docker build -t booker-api-test:latest -f ./BookerApiTest/Dockerfile .

    # Step 5: Run the container and execute tests
    - name: Run tests inside the container
      run: |
        pwd
        ls
        ls -la
        ls -la ./BookerApiTest/bin/Debug/net8.0
        ls -la ./BookerApiTest/bin/Debug/net8.0/allure-results
        rm -rf ./BookerApiTest/bin
        ls -la         
        echo ",,,,,,,,,,,,,,,---------------------------------------"
        docker run --rm booker-api-test:latest dotnet test --logger "trx;LogFileName=test-results.trx" || true
        #docker run --rm booker-api-test:latest allure generate /app/BookerApiTest/bin/Debug/net8.0/allure-results -o ./allure-report --clean
        #echo ",,,,,,,,,,,,,,22222222,,,"
        
        # Create directories for test results
        mkdir -p ./test-results ./allure-report
        
        # Run tests with volume mounts (ignore test failure exit code)
        # docker run --rm \
        #   -v $(pwd)/test-results:/app/BookerApiTest/TestResults \
        #   -v $(pwd)/allure-report:/app/allure-report \
        #   booker-api-test:latest \
        #   sh -c "dotnet test --logger 'trx;LogFileName=test-results.trx' || true && \
        #          allure generate /app/BookerApiTest/bin/Debug/net8.0/allure-results -o /app/allure-report --clean"
        
        # Display test results
        ls -la ./test-results
        ls -la ./allure-report

        ls -la
        pwd
        echo ",,,,,,,,,,,,,,,,,+++++++++++++++++++++++++++++++++++++++++++++"
        ls -la ./BookerApiTest/bin/Debug/net8.0
        ls -la ./BookerApiTest/bin/Debug/net8.0/allure-results

        

    # Step 5: Upload raw test results (.trx file)
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./BookerApiTest/TestResults/test-results.trx

    # Step 6: Upload Allure results
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./BookerApiTest/bin/Debug/net8.0/allure-results